kind: Route
apiVersion: route.openshift.io/v1
metadata:
  labels:
    app: cicd-dotnet-sample
  name: cicd-dotnet-sample
  namespace: dojo
spec:
  to:
    kind: Service
    name: cicd-dotnet-sample
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
